version: '3'

services:
  kafka:
    
    image: docker.io/bitnami/kafka:3.4
    ports:
      # - "9092:9092" Not required as the advertised port for network communication will be internal 
      - "19092:19092"
      - "9093:9093"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_ENABLE_KRAFT : yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093, EXTERNAL://0.0.0.0:19092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_CFG_LISTENER_NAMES: PLAINTEXT,CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093,2@kafka2:9096,3@kafka3:9095
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_ID: DVdLjeGBTgq4yeoPg_6_-g

      
    networks:
      - spark-kafka
  
  kafka2:
    
    image: docker.io/bitnami/kafka:3.4
    ports:
     # - "9094:9092" Not required as the advertised port for network communication will be internal 
      - "19094:19092"
      - "9096:9096"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_ENABLE_KRAFT : yes
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9096, EXTERNAL://0.0.0.0:19092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,EXTERNAL://localhost:19094
      KAFKA_CFG_LISTENER_NAMES: PLAINTEXT,CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093,2@kafka2:9096,3@kafka3:9095
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_ID: DVdLjeGBTgq4yeoPg_6_-g

      
    networks:
      - spark-kafka

  kafka3:
    
    image: docker.io/bitnami/kafka:3.4
    ports:
      # - "9097:9092"Not required as the advertised port for network communication will be internal 
      - "19095:19092"
      - "9095:9095"
    environment:
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_ENABLE_KRAFT : yes
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9095, EXTERNAL://0.0.0.0:19092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,EXTERNAL://localhost:19095
      KAFKA_CFG_LISTENER_NAMES: PLAINTEXT,CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093,2@kafka2:9096,3@kafka3:9095
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_KRAFT_CLUSTER_ID: DVdLjeGBTgq4yeoPg_6_-g
      
    networks:
      - spark-kafka
 

networks:
  spark-kafka:
    driver: bridge
